name: Automatic Review

on:
  pull_request_target:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  auto-review:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout PR code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Checkout Trusted Scripts
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.base_ref }}
          path: .trusted
          sparse-checkout: scripts/auto_review.js

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Run auto-review script
        id: check
        run: node .trusted/scripts/auto_review.js
        env:
          GITHUB_BASE_REF: ${{ github.base_ref }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
